on:
  pull_request:

name: Changelog Linter
jobs:
  lint:
    name: Lint Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint changesets
        run: node .changeset/lint.mjs
